name: Production CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  hasura:
    name: Deploy changes to Hasura
    runs-on: ubuntu-latest
    environment: Production
    env:
      HASURA_CLI_VERSION: "v2.0.4"
      HASURA_GRAPHQL_ENDPOINT: "https://geonotes-prod.herokuapp.com"
      HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Download Hasura CLI
        run: |
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
          sudo hasura update-cli --version ${HASURA_CLI_VERSION}
      - name: Apply migrations and metadata
        working-directory: hasura
        run: |
          hasura metadata apply
          hasura migrate apply --all-databases
          hasura metadata reload
  firebase:
    name: Deploy changes to Firebase
    runs-on: ubuntu-latest
    needs: hasura
    environment: Production
    env:
      FIREBASE_PROJECT_ID: "geonotes-prod"
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Download Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
      - name: Update environment configuration
        run: |
          firebase use ${FIREBASE_PROJECT_ID}
          firebase functions:config:get > .runtimeconfig.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Deploy
        run: firebase deploy
