name: Test optional chaining

on:
  push:
    branches:
      - test/optional-chaining

jobs:
  test:
    name: Test optional chaining
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          node -v
          node
          {}?.foo
